[package]
name = "hypersurface"
version = "0.1.0"
edition = "2021"

[dependencies]
zwohash = "0.1"

[dev-dependencies]
idek = { git = "https://github.com/Masterchef365/idek.git", rev = "6a5678f" }

[profile.release]
debug = true
